version: '3'

services:
  app:
    image: golang:1.15.1
    ports:
      - 8043:5001
    volumes:
      - ./../../../:/root/mgo
      - /var/www:/go
    working_dir: /root/mgo/micors/scrm
    command:
      - ./deploy/start_overseer.sh
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2g"
